"""'followers'

Revision ID: 199faab844e2
Revises: 332d0ab3766d
Create Date: 2020-04-16 18:09:02.482549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199faab844e2'
down_revision = '332d0ab3766d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
